name: Java CI - Compile and Test

# Trigger the workflow on pushes and pull requests
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Compile Java files
      - name: Compile Java files
        run: javac -d out $(find ./src -name "*.java")

      # Step 4: Run tests
      - name: Run tests
        run: java -cp out org.junit.runner.JUnitCore LoginAppTest
